### PR TITLE
update clang and cpp standard

### PR DESCRIPTION
**Pull request by kamiljoner**
Change clang version to clang17
Change default compiler from gcc to Clang
Change language standard to cpp23

### CODE REVIEW

**Comment by hparzych** [comment]
Just so you know, we reverted to using gcc instead of clang to reduce build times. When using clang the libraries are not available on conan cache and have to be built locally.

**Comment by kamiljoner** [comment]
> so that you know, we reverted to using gcc instead of clang to reduce build times. When using clang the libraries are not available on conan cache and have to be built locally.

It's not a real issue; whole build + test takes 8 minutes. Also, the longest build time is boost, which can be heavily reduced (If ever needed) by modifying boost to build only parts that we're really using since now it builds definitelly too much. This slight overhead is a a good tradeof to use and maintain only one compiler.

**Review by jakubrak — APPROVED** [review]
Glibc version is the same, right? I'm not much familiar how Clang handles that

**Comment by kamiljoner** [comment]
> Glibc version is the same, right? I'm not much familiar how Clang handles that

There should be no difference.

**Pull request merged**
